### ISSUE TITLE
::selection selektorundan istifadə edə bilərsiniz

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [sevilledev/portfolio-sevilledev#1]
[🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

```css
::selection {
    color: #10121b;
    background-color: #10121b;
}
```
Saytınızda qəşəng göründü. :)
